services:
  homework-tracker:
    image: hcktplanet/homework-tracker:latest
    container_name: homework-tracker
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma/prod.db
      - NEXTAUTH_URL=https://homework.metacto.com
      - SUPERADMINS=luciano.bargmann@metacto.com
    volumes:
      - homework_data:/app/prisma
    networks:
      - web
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  homework_data:

networks:
  web:
    driver: bridge