services:
  homework-tracker:
    build: .
    container_name: homework-tracker-local
    # entrypoint: ["/app/entrypoint-simple.sh"]
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - SUPERADMINS=${SUPERADMINS}
      - DATABASE_URL=file:/app/database/dev.db
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - SMTP_USER=
      - SMTP_PASS=
      - SMTP_FROM=homework@localhost
    volumes:
      - homework_local_db:/app/database
    depends_on:
      - mailpit
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit-local
    ports:
      - "8026:8025"  # Web UI
      - "1026:1025"  # SMTP
    restart: unless-stopped

volumes:
  homework_local_db: