services:
  homework-tracker:
    image: hcktplanet/homework-tracker:latest
    container_name: homework-tracker
    ports:
      - "80:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma/prod.db
      - NEXTAUTH_URL=https://homework.metacto.com
      - SUPERADMINS=luciano.bargmann@metacto.com
    volumes:
      - ec2-user_homework_data:/app/prisma
    networks:
      - web
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  ec2-user_homework_data:
    external: true

networks:
  web:
    driver: bridge